name: Build And Push
run-name: ${{ github.actor }} is runs ci pipeline
on:
  push:
    branches:
      - latest

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: git.meowly.ru
          username: ${{ secrets.CI_USERNAME }}
          password: ${{ secrets.CI_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Linter & Formatter
        run: uv run pre-commit run --all-files

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: "git.meowly.ru/minzdrav/telegramresender:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
